version: '3.4'

services:
  mongo:
    image: mongo
    # command: mongod --port 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo-client:
    image: mongo
    depends_on:
    - mongo
    volumes:
    - ./scripts:/scripts
    entrypoint:
    - /scripts/initiate_replica.sh
