version: '3.4'

services:
  mongo:
    image: mongo
    command: mongod --port 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}

  write-service:
    build: .
    volumes:
    - ./config:/config
    ports:
      - 4000:4000
