environments:
  dev:

repositories:
- name: yesodot
  url: https://harborreg-2.northeurope.cloudapp.azure.com/chartrepo/library
  username: {{ requiredEnv "HARBOR_USER" }}
  password: {{ requiredEnv "HARBOR_PASSWORD" }}
  
releases:
- name: write-service
  namespace: kartoffel
  chart: yesodot/common
  version: {{ requiredEnv "COMMON_VERSION" | default "0.1.0" }}
  # values:
  #   - ./write-service/values.yaml

helmDefaults:
  createNamespace: true