name: "write-service"
replicaCount: 1

images:
  PullSecrets: 
    name: kartoffelreg
  repository: genesisproject.azurecr.io/write-service
  tag: "latest"

volume:
  - name: gate-volume
    mountPath: /config/
    secretName: azure-secret 
    shareName: system-genesis/ 
    type: azurefile 
    
config:
  configmaps: 
    name: write-service
