name: "write-service"
replicaCount: 1

images:
  PullSecrets: 
    name: kartoffelreg
  repository: genesisproject.azurecr.io/write-service
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    
volume:
  - name: write-service-volume
    mountPath: /config
    secretName: azure-secret 
    shareName: system-genesis/write-service
    type: azurefile 
    
config:
  configmaps: 
    name: write-service
